"""updated

Revision ID: 5356630eaa32
Revises: 
Create Date: 2022-12-22 12:09:35.347813

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5356630eaa32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('is_system_user', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('account_number', sa.String(length=20), nullable=True),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('account_balance', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_number')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('account', sa.Integer(), nullable=False),
    sa.Column('to_account', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('trans_type', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account'], ['account.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_account'], ['account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('IS601_UserRoles', schema=None) as batch_op:
        batch_op.drop_index('role_id')

    op.drop_table('IS601_UserRoles')
    with op.batch_alter_table('IS601_Users', schema=None) as batch_op:
        batch_op.drop_index('email')
        batch_op.drop_index('username')

    op.drop_table('IS601_Users')
    with op.batch_alter_table('IS601_Roles', schema=None) as batch_op:
        batch_op.drop_index('name')

    op.drop_table('IS601_Roles')
    with op.batch_alter_table('IS601_Sample', schema=None) as batch_op:
        batch_op.drop_index('name')

    op.drop_table('IS601_Sample')
    with op.batch_alter_table('IS601_MP2_Companies', schema=None) as batch_op:
        batch_op.drop_index('name')

    op.drop_table('IS601_MP2_Companies')
    with op.batch_alter_table('IS601_MP2_Employees', schema=None) as batch_op:
        batch_op.drop_index('email')

    op.drop_table('IS601_MP2_Employees')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('IS601_MP2_Employees',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('company_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('email', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('modified', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['IS601_MP2_Companies.id'], name='IS601_MP2_Employees_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('IS601_MP2_Employees', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=False)

    op.create_table('IS601_MP2_Companies',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('address', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('city', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('country', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('state', mysql.VARCHAR(length=3), nullable=True),
    sa.Column('zip', mysql.VARCHAR(length=5), nullable=True),
    sa.Column('website', mysql.TEXT(), nullable=True),
    sa.Column('created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('modified', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('IS601_MP2_Companies', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=False)

    op.create_table('IS601_Sample',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('val', mysql.VARCHAR(length=40), nullable=True),
    sa.Column('created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('modified', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('IS601_Sample', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=False)

    op.create_table('IS601_Roles',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('modified', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('IS601_Roles', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=False)

    op.create_table('IS601_Users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('modified', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('IS601_Users', schema=None) as batch_op:
        batch_op.create_index('username', ['username'], unique=False)
        batch_op.create_index('email', ['email'], unique=False)

    op.create_table('IS601_UserRoles',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('role_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('modified', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('IS601_UserRoles', schema=None) as batch_op:
        batch_op.create_index('role_id', ['role_id', 'user_id'], unique=False)

    op.drop_table('transaction')
    op.drop_table('account')
    op.drop_table('user')
    # ### end Alembic commands ###
